name: "Deploy iOS to TestFlight/App Store"
description: "Download IPA artifact and upload to App Store Connect using iTMSTransporter"

inputs:
  artifact-name:
    description: "Name of the artifact to download (e.g., iOS)"
    required: true
  game-name:
    description: "Game name used for the artifact filename (expects <game-name>.ipa)"
    required: true
  apple-id:
    description: "Apple ID (username) for App Store Connect"
    required: true
  app-specific-password:
    description: "App-specific password for the Apple ID"
    required: true
  itc-provider:
    description: "Optional provider short name if Apple ID has multiple teams"
    required: false
    default: ""
  verbose:
    description: "Enable detailed transporter logs"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    - name: 📥 Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: build

    - name: Publish the App on TestFlight
      shell: bash
      working-directory: build
      run: |
        xcrun altool --upload-app --type ios --file ${{ inputs.game-name }}.ipa \
        --username "${{ inputs.apple-id }}" --password "${{ inputs.app-specific-password }}" --verbose
