name: Deploy Godot Game to Steam.

on:
  workflow_call:
    secrets:
      steam-username:
        description: >-
          Steam username to use for authentication. This is used to log in to
          Steam and deploy the game. Eg. username
        required: true
      steam-password:
        description: >-
          Steam password to use for authentication. This is used to log in to
          Steam and deploy the game. Eg. password
        required: true
      steam-shared-secret:
        description: >-
          Steam shared secret for two-factor authentication. This is used to
          authenticate the deployment process. You can find this in your Steam
          account settings. Eg. ABCDEFGHIJKLMNOPQRSTUVWX
        required: true
    inputs:
      game-version:
        type: string
        description: >-
          Version of the game to deploy. This is used in the build description.
          Eg. 1.0.0
        required: true
      steam-win64-depot-id:
        type: string
        description: >-
          Steam depot ID for the Windows 64-bit build. Eg. 123456
        required: true
      steam-win32-depot-id:
        type: string
        description: >-
          Steam depot ID for the Windows 32-bit build. Eg. 123457
        required: true
      steam-linux64-depot-id:
        type: string
        description: >-
          Steam depot ID for the Linux 64-bit build. Eg. 123458
        required: true
      steam-linux32-depot-id:
        type: string
        description: >-
          Steam depot ID for the Linux 32-bit build. Eg. 123459
        required: true
      steam-mac-depot-id:
        type: string
        description: >-
          Steam depot ID for the macOS build. Eg. 123460
        required: true
      steam-app-id:
        type: string
        description: >-
          Steam application ID for the game. This is used to identify the game
          on Steam. Eg. 1234567
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 游닌 Download Linux x86_64
        uses: actions/download-artifact@v4
        with:
          name: "Linux x86_64-steam"
          path: build_linux_x86_64
      - name: 游닌 Download Linux x86_32
        uses: actions/download-artifact@v4
        with:
          name: "Linux x86_32-steam"
          path: build_linux_x86_32
      - name: 游닌 Download macOS
        uses: actions/download-artifact@v4
        with:
          name: "macOS-steam"
          path: build_macos
      - name: 游닌 Download Windows Desktop x86_64
        uses: actions/download-artifact@v4
        with:
          name: "Windows Desktop x86_64-steam"
          path: build_windows_x86_64
      - name: 游닌 Download Windows Desktop x86_32
        uses: actions/download-artifact@v4
        with:
          name: "Windows Desktop x86_32-steam"
          path: build_windows_x86_32
      
      - name: Deploy to Steam via composite action
        uses: ./.github/actions/deploy-steam
        with:
          steam-username: ${{ secrets.steam-username }}
          steam-password: ${{ secrets.steam-password }}
          steam-shared-secret: ${{ secrets.steam-shared-secret }}
          game-version: ${{ inputs.game-version }}
          steam-app-id: ${{ inputs.steam-app-id }}
          steam-win64-depot-id: ${{ inputs.steam-win64-depot-id }}
          steam-win32-depot-id: ${{ inputs.steam-win32-depot-id }}
          steam-linux64-depot-id: ${{ inputs.steam-linux64-depot-id }}
          steam-linux32-depot-id: ${{ inputs.steam-linux32-depot-id }}
          steam-mac-depot-id: ${{ inputs.steam-mac-depot-id }}
