name: Deploy Blazium Android Game to Play Store.

on:
  workflow_call:
    secrets:
      service-account-json-base64:
        description: >-
          Base64 encoded service account JSON file for Google Play Store
          authentication.
        required: true
    inputs:
      artifact-name:
        type: string
        description: >-
          Name of the artifact to download. Eg. Android
        required: true
      android-package:
        type: string
        description: >-
          Package name of the Android application. Eg. com.example.app
        required: true
      game-name:
        type: string
        description: >-
          Name of the game, used for the artifact name. Eg. MyGame
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 📥 Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: build
      
      - name: Copy service account
        shell: bash
        run: |
          echo -n "${{ secrets.service-account-json-base64 }}" | base64 --decode >> service-account.json

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service-account.json
          packageName: ${{ inputs.android-package }}
          releaseFiles: build/${{ inputs.game-name }}.aab
          track: "internal"
          status: draft
