name: Deploy Godot Game to itch.io.

on:
  workflow_call:
    secrets:
      butler-credentials:
        description: >-
          Butler credentials to use for authentication.
        required: true
    inputs:
      itchio-username:
        type: string
        description: >-
          Itch.io username to use for authentication. Eg. username
        required: true
      itchio-game:
        type: string
        description: >-
          Itch.io game slug to deploy to. Eg. game-slug
        required: true
      artifact-name:
        type: string
        description: >-
          Name of the artifact to download. Eg. Linux x86_64

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to itch.io via composite action
        uses: ./.github/actions/deploy-itchio
        with:
          artifact-name: ${{ inputs.artifact-name }}
          itchio-username: ${{ inputs.itchio-username }}
          itchio-game: ${{ inputs.itchio-game }}
          butler-credentials: ${{ secrets.butler-credentials }}
  