name: Deploy Godot iOS Game to App Store.

on:
  workflow_call:
    secrets:
      apple-id:
        description: >-
          Apple ID to use for authentication. Eg.
        required: true
      app-specific-password:
        description: >-
          App-specific password for the Apple ID. This is required for
          uploading to TestFlight. You can generate it from your Apple ID
          account page.
        required: true
    inputs:
      artifact-name:
        type: string
        description: >-
          Name of the artifact to download. Eg. Web
        required: true
      game-name:
        type: string
        description: >-
          Name of the game, used for the artifact name. Eg. MyGame
        required: true

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Deploy iOS via composite action
        uses: ./.github/actions/deploy-ios
        with:
          artifact-name: ${{ inputs.artifact-name }}
          game-name: ${{ inputs.game-name }}
          apple-id: ${{ secrets.apple-id }}
          app-specific-password: ${{ secrets.app-specific-password }}
          verbose: "true"
    