name: Deploy Godot macOS Game to App Store.

on:
  workflow_call:
    secrets:
      apple-id:
        description: >-
          Apple ID to use for authentication. Eg.
        required: true
      apple-team-id:
        description: >-
          Apple Team ID for the application. This is used in the signing
          process.
        required: true
      app-specific-password:
        description: >-
          App-specific password for the Apple ID. This is required for
          uploading to TestFlight. You can generate it from your Apple ID
          account page.
        required: true
      deploy-certificate-base64:
        description: >-
          Base64 encoded deploy certificate for macOS application signing.
        required: true
      install-certificate-base64:
        description: >-
          Base64 encoded install certificate for macOS application signing.
        required: true
      p12-password:
        description: >-
          Password for the P12 certificate files used in signing.
        required: true
      deploy-provisioning-profile-mac-base64:
        description: >-
          Base64 encoded provisioning profile for macOS application deployment.
        required: true
      keychain-password:
        description: >-
          Password for the keychain used during the signing process.
        required: true
    inputs:
      artifact-name:
        type: string
        description: >-
          Name of the artifact to download. Eg. macOS
        required: true
      game-name:
        type: string
        description: >-
          Name of the game, used for the artifact name. Eg. MyGame
        required: true
      macos-package:
        type: string
        description: >-
          iOS package name to use in the entitlements file. This is used for
          signing the application. Eg. com.example.app
        required: true

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Deploy macOS via composite action
        uses: ./.github/actions/deploy-macos
        with:
          artifact-name: ${{ inputs.artifact-name }}
          game-name: ${{ inputs.game-name }}
          macos-package: ${{ inputs.macos-package }}
          apple-team-id: ${{ secrets.apple-team-id }}
          deploy-certificate-base64: ${{ secrets.deploy-certificate-base64 }}
          install-certificate-base64: ${{ secrets.install-certificate-base64 }}
          p12-password: ${{ secrets.p12-password }}
          deploy-provisioning-profile-mac-base64: ${{ secrets.deploy-provisioning-profile-mac-base64 }}
          keychain-password: ${{ secrets.keychain-password }}
          apple-id: ${{ secrets.apple-id }}
          app-specific-password: ${{ secrets.app-specific-password }}
